version: '3.8'

services:
  # Image Gallery Application (SQLite version)
  app:
    build: .
    container_name: image-gallery-app-simple
    ports:
      - "5002:5002"
    environment:
      # Flask Configuration
      - SECRET_KEY=${SECRET_KEY:-change-this-to-a-random-secret-key}
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5002
      
      # Database Configuration (SQLite)
      - DATABASE_TYPE=sqlite
      - SQLITE_DATABASE=/app/data/images.db
      
      # Application Settings
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-16777216}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-jpg,jpeg,png,gif}
      - DEFAULT_PAGINATION=${DEFAULT_PAGINATION:-8}
      - MAX_IMAGES=${MAX_IMAGES:-100}
      
      # LAION Dataset Configuration
      - LAION_CSV_FILE=laion_sample.csv
      - MAX_WORKERS=${MAX_WORKERS:-4}
      - DOWNLOAD_TIMEOUT=${DOWNLOAD_TIMEOUT:-15}
    volumes:
      - app_data:/app/data
      - uploads:/app/static/uploads
      - ./laion_sample.csv:/app/laion_sample.csv:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  app_data:
    driver: local
  uploads:
    driver: local

networks:
  default:
    name: image-gallery-simple-network
